### ISSUE TITLE
Cannot wake up panel_xiaomi_nt35532 on mido

### ISSUE THREAD

**Issue by barni2000** [msm8953-mainline/linux#113]
After panel goes to sleep it cannot be waken up only the backlights works.

**Comment by Kiciuk** [comment]
seems to be some kind of universal issue not tied to exact panel.
Dmesg should cry about -22 on panel initialize or something

**Comment by barni2000** [comment]
> seems to be some kind of universal issue not tied to exact panel. Dmesg should cry about -22 on panel initialize or something

I have got same message on every msm8953 device i have with every panel but other panels are waking up for me.

**Comment by barni2000** [comment]
It seems working now with 6.4/main branch.
