### ISSUE TITLE
Question about config

### ISSUE THREAD

**Issue by Slavatar2001** [msm8953-mainline/linux#130]
Hi all! I have a question, every update of the kernel version I have to build my own kernel, to add an external usb wifi adapter mt7601u driver, will there ever be usb_wifi.config or full.config, for example, to make a full-fledged PC (or PDA, whatever you like) . In the kernel, almost everything is disabled, supposedly superfluous, more like the android kernel. I would like pmos to be, like other linux distributions in which almost everything is included in the kernel. And not to build the kernel on my own for the equipment I need, but what would such a kernel be publicly available to everyone in the main update repository.

**Comment by alikates** [comment]
Hi. If you need to enable some config in pmos, please open a MR in [pmaports](https://gitlab.com/postmarketOS/pmaports) repo. The packaged kernel uses a configuration that is manually created by merging all device config fragments and tweaking some things that are not updated here.
