### ISSUE TITLE
msm8953 6.5.2 kernel gpu cannot be used in mobian system! System graphics card display software rendering can't use gpu.

### ISSUE THREAD

**Issue by wu17481748** [msm8953-mainline/linux#144]
[    1.258101] adreno 1c00000.gpu: Adding to iommu group 0                 [    1.258761] i2c_qup 78b6000.i2c: using default clock-frequency 100000   [    1.258793] i2c_qup 78b6000.i2c:                                                        tx channel not available                                   [    1.259163] i2c_qup 78b7000.i2c: using default clock-frequency 100000   [    1.259184] i2c_qup 78b7000.i2c:                                                        tx channel not available                                   [    1.288999] platform 1a94000.dsi: Fixed dependency cycle(s) with /soc@0/display-subsystem@1a00000/dsi@1a94000/panel@0/port/endpoint                [    1.289067] platform 1a94000.dsi: Fixed dependency cycle(s) with /soc@0/display-subsystem@1a00000/display-controller@1a01000/ports/port@0/endpoint [    1.293871] i2c_qup 78b6000.i2c: using default clock-frequency 100000   [    1.293914] i2c_qup 78b6000.i2c:                                                        tx channel not available                                   [    1.294423] i2c_qup 78b7000.i2c: using default clock-frequency 100000   [    1.294468] i2c_qup 78b7000.i2c:                                                        tx channel not available                                   [    1.295607] msm_mdp 1a01000.display-controller: Adding to iommu group 1 [    1.305731] mipi-dsi 1a94000.dsi.0: Fixed dependency cycle(s) with /soc@0/display-subsystem@1a00000/dsi@1a94000/ports/port@1/endpoint              [    1.307376] i2c_qup 78b6000.i2c: using default clock-frequency 100000   [    1.307418] i2c_qup 78b6000.i2c:                                                        tx channel not available                                   [    1.307822] i2c_qup 78b7000.i2c: using default clock-frequency 100000   [    1.307844] i2c_qup 78b7000.i2c:                                                        tx channel not available                                   [    1.308619] msm_mdp 1a01000.display-controller: bound 1a94000.dsi (ops dsi_ops [msm])                                                              [    1.310060] adreno 1c00000.gpu: supply vdd not found, using dummy regulator                                                                        [    1.310208] adreno 1c00000.gpu: supply vddcx not found, using dummy regulator                                                                      [    1.315708] msm_mdp 1a01000.display-controller: bound 1c00000.gpu (ops a3xx_ops [msm])                                                             [    1.316031] msm_mdp 1a01000.display-controller: [drm:mdp5_kms_init [msm]] MDP5 version v1.16                                                       [    1.335166] [drm] Initialized msm 1.10.0 20130625 for 1a01000.display-controller on minor 0                                                        [    1.335640] msm_mdp 1a01000.display-controller: Direct firmware load for qcom/a530_pm4.fw failed with error -2                                     [    1.335678] msm_mdp 1a01000.display-controller: [drm:adreno_request_fw [msm]] *ERROR* failed to load a530_pm4.fw                                   [    1.420083] [drm:mdp5_irq_error_handler [msm]] *ERROR* errors: 04000000 [    1.732228] Console: switching to colour frame buffer device 135x120    [    1.764915] msm_mdp 1a01000.display-controller: [drm] fb0: msmdrmfb frame buffer device

**Comment by vldly** [comment]
`[ 1.335640] msm_mdp 1a01000.display-controller: Direct firmware load for qcom/a530_pm4.fw failed with error -2`
According to this it can't find proprietary firmware files. Those files are part of [linux-firmware](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/qcom) package. Also this adreno GPU will require a506_zap.* which can be pulled only from device file-system (because it's crypto-graphically signed).

**Comment by wu17481748** [comment]
> `[ 1.335640] msm_mdp 1a01000.display-controller: Direct firmware load for qcom/a530_pm4.fw failed with error -2` According to this it can't find proprietary firmware files. Those files are part of [linux-firmware](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/qcom) package. Also this adreno GPU will require a506_zap.* which can be pulled only from device file-system (because it's crypto-graphically signed).



My previous 6.3 kernel works normally with this firmware gpu! This firmware comes from postmarketos system. Thank you. I'll try this firmware you mentioned!

**Comment by vldly** [comment]
> > `[ 1.335640] msm_mdp 1a01000.display-controller: Direct firmware load for qcom/a530_pm4.fw failed with error -2` According to this it can't find proprietary firmware files. Those files are part of [linux-firmware](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/qcom) package. Also this adreno GPU will require a506_zap.* which can be pulled only from device file-system (because it's crypto-graphically signed).
> 
> My previous 6.3 kernel works normally with this firmware gpu! This firmware comes from postmarketos system. Thank you. I'll try this firmware you mentioned!

This was only based on the log. Another reason could be that mobian mesa version it too old (A506 was recently whitelisted) and we dropped [patch](https://github.com/msm8953-mainline/linux/commit/3c181c25e8355d641a711dc5da4ab35b1b5a64fb) which presented this GPU as A530 to userspace.

**Comment by wu17481748** [comment]
> > > `[ 1.335640] msm_mdp 1a01000.display-controller: Direct firmware load for qcom/a530_pm4.fw failed with error -2` According to this it can't find proprietary firmware files. Those files are part of [linux-firmware](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/qcom) package. Also this adreno GPU will require a506_zap.* which can be pulled only from device file-system (because it's crypto-graphically signed).
> > 
> > 
> > My previous 6.3 kernel works normally with this firmware gpu! This firmware comes from postmarketos system. Thank you. I'll try this firmware you mentioned!
> 
> This was only based on the log. Another reason could be that mobian mesa version it too old (A506 was recently whitelisted) and we dropped [patch](https://github.com/msm8953-mainline/linux/commit/3c181c25e8355d641a711dc5da4ab35b1b5a64fb) which presented this GPU as A530 to userspace.


Gpu still can't use the log after replacing the 530 firmware.


[   16.352737] msm_mdp 1a01000.display-controller: [drm:adreno_request_fw [msm]] loaded qcom/a530_pm4.fw from new location                                     [   16.354187] msm_mdp 1a01000.display-controller: [drm:adreno_request_fw [msm]] loaded qcom/a530_pfp.fw from new location                                     [   16.363388] *** gpu fault: iova=0000000001047dc0 flags=0 (0,0,0,0)                                     [   16.363414] qcom-iommu-ctx 1c48000.iommu-ctx: Unhandled context fault: fsr=0x40000202, iova=0x0000000001047dc0, fsynr=0x3, cb=0                             [   16.363432] *** gpu fault: iova=0000000001047de0 flags=0 (0,0,0,0)
[   16.363444] qcom-iommu-ctx 1c48000.iommu-ctx: Unhandled context fault: fsr=0x40000202, iova=0x0000000001047de0, fsynr=0x3, cb=0
[   16.363460] *** gpu fault: iova=0000000001047e00 flags=0 (0,0,0,0)                                     [   16.363472] qcom-iommu-ctx 1c48000.iommu-ctx: Unhandled context fault: fsr=0x40000202, iova=0x0000000001047e00, fsynr=0x3, cb=0
[   16.363488] *** gpu fault: iova=0000000001047e20 flags=0 (0,0,0,0)
[   16.363500] qcom-iommu-ctx 1c48000.iommu-ctx: Unhandled context fault: fsr=0x40000202, iova=0x0000000001047e20, fsynr=0x3, cb=0                             [   16.363516] *** gpu fault: iova=0000000001047e40 flags=0 (0,0,0,0)                                     [   16.363527] qcom-iommu-ctx 1c48000.iommu-ctx: Unhandled context fault: fsr=0x40000202, iova=0x0000000001047e40, fsynr=0x3, cb=0                             [   16.363543] *** gpu fault: iova=0000000001047e60 flags=0 (0,0,0,0)                                     [   16.363555] qcom-iommu-ctx 1c48000.iommu-ctx: Unhandled context fault: fsr=0x40000202, iova=0x0000000001047e60, fsynr=0x3, cb=0                             [   16.363571] *** gpu fault: iova=0000000001047e80 flags=0 (0,0,0,0)                                     [   16.363582] qcom-iommu-ctx 1c48000.iommu-ctx: Unhandled context fault: fsr=0x40000202, iova=0x0000000001047e80, fsynr=0x3, cb=0                             [   16.363601] *** gpu fault: iova=0000000001047ea0 flags=0 (0,0,0,0)                                     [   16.363613] qcom-iommu-ctx 1c48000.iommu-ctx: Unhandled context fault: fsr=0x40000202, iova=0x0000000001047ea0, fsynr=0x3, cb=0                             [   16.363629] *** gpu fault: iova=0000000001047ec0 flags=0 (0,0,0,0)                                     [   16.363640] qcom-iommu-ctx 1c48000.iommu-ctx: Unhandled context fault: fsr=0x40000202, iova=0x0000000001047ec0, fsynr=0x3, cb=0                             [   16.363656] *** gpu fault: iova=0000000001047ee0 flags=0 (0,0,0,0)                                     [   16.363667] qcom-iommu-ctx 1c48000.iommu-ctx: Unhandled context fault: fsr=0x40000202, iova=0x0000000001047ee0, fsynr=0x3, cb=0
[   17.359816] [drm:adreno_idle [msm]] *ERROR* A506: timeout waiting to drain ringbuffer 0 rptr/wptr = 0/9[   17.359991] msm_mdp 1a01000.display-controller: RBBM | AHB bus error | WRITE | addr=0x2F27 | ports=0x1:0xF                                                  [   17.360010] msm_mdp 1a01000.display-controller: CP | AHB error | addr=BC9C access=me write error=-2147483648 | status=0x8900BC9C
[   17.359989] msm_mdp 1a01000.display-controller: [drm:adreno_load_gpu [msm]] *ERROR* gpu hw init failed: -22

**Comment by SeamusCheng** [comment]
Did you solve this problem now？

**Comment by wu17481748** [comment]
> Did you solve this problem now？

没有
