### ISSUE TITLE
USB Type-C support with PMI632

### ISSUE THREAD

**Issue by z3ntu** [msm8953-mainline/linux#159]
FYI for devices with PMI632, USB role switching should work with the following patch series: https://lore.kernel.org/linux-arm-msm/20240113-pmi632-typec-v2-0-182d9aa0a5b3@linaro.org/

Tested on Fairphone 3 (SDM632+PMI632). Since the series depends on some more patches that are only in v6.8-rc1, I'm probably going to add the patches the repo here only a bit later to reduce conflicts.

https://github.com/z3ntu/linux/commits/fp3-6.8-typec/

**Comment by barni2000** [comment]
@z3ntu as far as i know it is already merged on 6.8.2 and also in 6.9 wip branch.
If it still needed to be tracked feel free reopen this ticket.
