### ISSUE TITLE
PostmarketOS battery status 

### ISSUE THREAD

**Issue by Donieck** [msm8953-mainline/linux#207]
I have a problem with battery status on kernel 6.9.1-postmarketos-qcom-msm8953. This is plasma mobile ![IMG_20240714_195525_469.jpg](https://github.com/user-attachments/assets/1e554b0c-a57a-4972-a91c-233595a533db)

![IMG_20240714_194609_014.jpg](https://github.com/user-attachments/assets/16a61ea7-97f3-4fe9-ad43-a15df647faf9)

**Comment by Donieck** [comment]
[dmesg.txt](https://github.com/user-attachments/files/16241487/dmesg.txt)

**Comment by barni2000** [comment]
This is know bug of the fg driver couple of reboot will solve your problem.
