### ISSUE TITLE
Unable to connect to 40mhz wifi.

### ISSUE THREAD

**Issue by sushen339** [msm8953-mainline/linux#208]
My device is markw, and I use postmarketOS system, and I found that I can't connect to 40mhz wifi.
![IMG_20240723_192923](https://github.com/user-attachments/assets/9566b117-48fd-4e6c-a621-64fc00904388)

Thank you very much for porting to msm8953, which makes my equipment alive again.

**Comment by barni2000** [comment]
It can, but wifi driver has some instability. Try to reconnect multiple times.
