### ISSUE TITLE
Please enable Alsa sequencer

### ISSUE THREAD

**Issue by vacuumbeef** [msm8953-mainline/linux#210]
Hello, I wanted to use my Xiaomi Redmi Note 4 (xiaomi-mido) for some music fiddling, and I need to send midi from one app to another, but I can't:
```
ALSA lib seq_hw.c:528:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
```

**Comment by barni2000** [comment]
Please open a ticket for https://gitlab.com/postmarketOS/pmaports/-/issues
