### ISSUE TITLE
Upstream MDSS support

### ISSUE THREAD

**Issue by z3ntu** [msm8953-mainline/linux#37]
I prepared a branch based on linux-next with only MDSS support and some extra patches that are probably needed (some maybe could be removed, not sure): https://github.com/z3ntu/linux/commits/msm8953-5.17-next-dsi3

@vldly Could you please answer these questions?

> drm/msm/mdp5: Add perf data for MDP v1.16

Looks clear, any objection to send?

> drm/msm/dsi: Use single function for reset

Not 100% sure why this exists, "However this assumtion is not true mobile devices which have boot splash set up by boot-loader." this literally applies to all smartphones I believe, why is this a problem on 8953?

> clk: qcom: rcg2: round parent rate when SET_RATE_PARENT is set

no description (what does this commit do?), missing sign-off

> clk: qcom: Don't update rcg2 when configuration wasn't changed

no description (what does this commit do?), missing sign-off

> iommu: qcom-iommu: avoid bouncing power domain

no description (what does this commit do?), missing sign-off

> soc: qcom: rpmpd: add hack to speed up suspend/resume

what does this commit improve, can we remove it?

> Revert "Revert "drm/msm/mdp5: provide dynamic bandwidth management""

can we remove this?

> firmware: qcom_scm: add support for smmu_change_pt_format

dependency for "iommu: arm-smmu-qcom: Add MSM8953 impl", missing description and sign-off though

> iommu: arm-smmu: add prepare implementation callback

dependency for "iommu: arm-smmu-qcom: Add MSM8953 impl", missing description and sign-off though

> iommu: arm-smmu-qcom: Add MSM8953 impl

not too familiar with iommu but looks ok, missing description and sign-off though

> arm64: dts: qcom: msm8953: add IOMMUs

clear, missing sign-off

> arm64: dts: qcom: msm8953: add MDSS

clear, missing sign-off

**Comment by vldly** [comment]
> I prepared a branch based on linux-next with only MDSS support and some extra patches that are probably needed (some maybe could be removed, not sure): https://github.com/z3ntu/linux/commits/msm8953-5.17-next-dsi3
> 
> @vldly Could you please answer these questions?
> 
> > drm/msm/mdp5: Add perf data for MDP v1.16
> 
> Looks clear, any objection to send?

No.

> > drm/msm/dsi: Use single function for reset
> 
> Not 100% sure why this exists, "However this assumtion is not true mobile devices which have boot splash set up by boot-loader." this literally applies to all smartphones I believe, why is this a problem on 8953?

It's not a problem. This is refactoring change, there is no need for two resets. 
 
> > clk: qcom: rcg2: round parent rate when SET_RATE_PARENT is set
> 
> no description (what does this commit do?), missing sign-off
> 
> > clk: qcom: Don't update rcg2 when configuration wasn't changed
> no description (what does this commit do?), missing sign-off

This is a fix for false `rcg didn't update its configuration` WARNs.

> > iommu: qcom-iommu: avoid bouncing power domain
> 
> no description (what does this commit do?), missing sign-off

Read comment (copied from arm-smmu.c). Also it isn't as bad in qcom-iommu's case.

> > soc: qcom: rpmpd: add hack to speed up suspend/resume
>
> what does this commit improve, can we remove it?

It fixes system suspend and resume time from few seconds. It can't receive answer from RPM with because smd needs interrupts to be enabled.
 
> > Revert "Revert "drm/msm/mdp5: provide dynamic bandwidth management""
> 
> can we remove this?

Yes, but why?

> > firmware: qcom_scm: add support for smmu_change_pt_format
> 

This call was upstreamed by Angelo. 

> dependency for "iommu: arm-smmu-qcom: Add MSM8953 impl", missing description and sign-off though
> 
> > iommu: arm-smmu: add prepare implementation callback
> 
> dependency for "iommu: arm-smmu-qcom: Add MSM8953 impl", missing description and sign-off though
> 
> > iommu: arm-smmu-qcom: Add MSM8953 impl
> 
> not too familiar with iommu but looks ok

Not for me.

**Comment by z3ntu** [comment]
There was some more IOMMU sent to the lists, maybe this is somewhat useful.. https://lore.kernel.org/linux-arm-msm/20220527212901.29268-1-konrad.dybcio@somainline.org/

**Comment by z3ntu** [comment]
Sent v1: https://lore.kernel.org/linux-arm-msm/20220610225304.267508-1-luca@z3ntu.xyz/t/

I've prepared v2 which includes apps_iommu and fixes the review comments from v1. I'll send soon

**Comment by z3ntu** [comment]
v3 has been sent with a minor change, one change from v2 has been picked up already: https://lore.kernel.org/linux-arm-msm/20220906183334.203787-1-luca@z3ntu.xyz/T/

**Comment by z3ntu** [comment]
Finally applied with v4: https://lore.kernel.org/linux-arm-msm/20221016161554.673006-1-luca@z3ntu.xyz/T/#m1ce819069abcdb27ecfbcdcc8c72a781bd758319
