### ISSUE TITLE
[PROPOSAL] Xiaomi Redmi Note 5 / Plus support

### ISSUE THREAD

**Issue by M0Rf30** [msm8953-mainline/linux#5]
Hi @Junak ,
hereby I want to propose support for another device powered by the msm8953 SoC. I'm talking about the Xiaomi Redmi Note 5 / Plus (codename vince). I am currently maintaining the downstream kernel for PostmarketOS and would be more than happy to test your efforts.
The most popular and fully working kernel repo for vince is [here](https://github.com/Blacksuan19/android_vendor_xiaomi_vince)
and another great kernel (with some cherry-picks from 4.14) is [here](https://github.com/stormbreaker-project/android_kernel_xiaomi_vince)
Best regards and thanks for all your hard work done until now

**Comment by Kiciuk** [comment]
I don't really think Junak is doing porting requests.
If you want to get Vince to mainline you need to create device tree yourself.
Feel free to join #mainline room on postmarketos.org matrix,ppl here might help you get things going.

**Comment by M0Rf30** [comment]
Ok. I will try
