### ISSUE TITLE
v6.1.0 testing

### ISSUE THREAD

**Issue by alikates** [msm8953-mainline/linux#72]
Hi, can we get the kernel tested on all devices so we can update the aport package?

Tested on:
- [ ] mido
- [x] daisy
- [ ] tissot
- [ ] ocean
- [x] vince
- [ ] fp3
- [ ] a6plte

(tell me if i'm missing any)

**Comment by M0Rf30** [comment]
Done. need to add this https://github.com/msm8953-mainline/linux/pull/71
it will fixes errors encountered on regions overlap.

**Comment by alikates** [comment]
I just merged your PR. I also cherry-picked the fixes for the missing sound cards.

**Comment by M0Rf30** [comment]
Thanks. I updated also pmaports MR
Could be useful to share built apk that will be available here (at the end of CI process)
https://gitlab.com/M0Rf30/pmaports/-/jobs/3568527126

**Comment by z3ntu** [comment]
I believe we can close this now since 6.1 has been merged in pmaports?
